FROM eclipse-temurin:17-jdk as build
WORKDIR /app
COPY src/server /app/src/server
# Simple compilation since it's just a few files without dependencies
RUN mkdir -p bin
RUN javac -d bin src/server/*.java

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/bin /app/bin
# Create scores.txt so it exists
RUN touch scores.txt
EXPOSE 5000/udp
ENTRYPOINT ["java", "-cp", "bin", "server.Server", "5000"]
